In [1]:
import torch

## `torch.einsum() ` 爱因斯坦求和约定

- https://zhuanlan.zhihu.com/p/44954540

In [2]:
a = torch.arange(6).reshape(2,3)
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [3]:
# 转置
b = torch.einsum('ij->ji', [a])  # 不会改变 a 的值
b

tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [4]:
# 求和
torch.einsum('ij->', [a])

tensor(15)

In [5]:
# 沿列求和，消去 j
torch.einsum('ij->i', [a])

tensor([ 3, 12])

In [6]:
# 沿行求和，消去 i
torch.einsum('ij->j', [a])

tensor([3, 5, 7])

In [7]:
# 矩阵相乘
a = torch.arange(6).reshape(2, 3)
b = torch.arange(15).reshape(3, 5)
torch.einsum('ij,jk->ik', [a, b])  # -> 左侧代表了 参与计算的元素个数

tensor([[ 25,  28,  31,  34,  37],
        [ 70,  82,  94, 106, 118]])

In [8]:
a = torch.arange(6).reshape(2, 3)
b = torch.arange(15).reshape(3, 5)
c = torch.arange(15).reshape(5, 3)
torch.einsum('ij,jk,km->im', [a, b, c])

tensor([[1020, 1175, 1330],
        [3180, 3650, 4120]])

In [9]:
# 向量 点积 数量积 标量积，得到实数
a = torch.arange(3)
b = torch.arange(3, 6)
res = torch.einsum('i,i->', [a,b])
print(res)
print(a*b)

tensor(14)
tensor([ 0,  4, 10])


In [10]:
# 矩阵点积 对应元素相乘求和
a = torch.arange(6).reshape(2, 3)
b = torch.arange(6,12).reshape(2, 3)
res = torch.einsum('ij,ij->', [a, b])
print(res)
print(torch.sum(a*b))

tensor(145)
tensor(145)


In [12]:
# hadamard 哈达玛积 element-wise product
print(torch.einsum('ij,ij->ij', [a,b]))
print(a*b)

tensor([[ 0,  7, 16],
        [27, 40, 55]])
tensor([[ 0,  7, 16],
        [27, 40, 55]])


In [13]:
# 外积
a = torch.arange(3)
b = torch.arange(3,7)
print(a)
print(b)
torch.einsum('i,j->ij', [a, b])  # 向量 -> 矩阵

tensor([0, 1, 2])
tensor([3, 4, 5, 6])


tensor([[ 0,  0,  0,  0],
        [ 3,  4,  5,  6],
        [ 6,  8, 10, 12]])

In [24]:
# 矩阵 * 行向量
a.reshape(3,1).repeat(1,4) * b

tensor([[ 0,  0,  0,  0],
        [ 3,  4,  5,  6],
        [ 6,  8, 10, 12]])

In [25]:
# batch 矩阵相乘
a = torch.randn(3,2,5)
b = torch.randn(3,5,3)
# jk, kl -> jl, i 作为 batch 不变
torch.einsum('ijk,ikl->ijl', [a, b])  # 3,2,3

tensor([[[-1.1521,  0.6876,  0.2198],
         [-1.3261, -2.3821,  1.9830]],

        [[-1.7016, -1.2594, -5.2988],
         [-3.9042, -2.7346,  0.5616]],

        [[-0.4510,  2.4994, -4.0824],
         [ 5.6344,  6.4358, -1.0691]]])

In [26]:
# 张量缩约
a = torch.randn(2,3,5,7)
b = torch.randn(11,13,3,17,5)
torch.einsum('pqrs,tuqvr->pstuv', [a, b]).shape  # 3,5 相等的 dim 约去

torch.Size([2, 7, 11, 13, 17])

In [ ]:
n, p = 10, 3

a = torch.randn(n, p)
print(torch.cov)